package org.maple.profitsystem.models;

import java.util.Date;

import org.maple.profitsystem.constants.CommonConstants;

public class CompanyStatisticsModel {
	
	public boolean isEmpty() {
		return this.insiderOwnPerc == null && this.instOwnPerc == null && this.shsFloat == null && this.shsOutstand == null;
	}
	
	/**
	 * Set the properties of this using target.
	 * 
	 * @param targert
	 * @return The number of different value between this and target.
	 */
	public int set(CompanyStatisticsModel target) {
		int count = 0;
		if(target == null) {
			return count;
		} else {
			if(target.insiderOwnPerc != null && target.insiderOwnPerc != this.insiderOwnPerc) {
				this.insiderOwnPerc = target.insiderOwnPerc;
				++count;
			}
			
			if(target.instOwnPerc != null && target.instOwnPerc != this.instOwnPerc) {
				this.instOwnPerc = target.instOwnPerc;
				++count;
			}
			
			if(target.shsOutstand != null && target.shsOutstand != this.shsOutstand) {
				this.shsOutstand = target.shsOutstand;
				++count;
			}
			
			if(target.shsFloat != null && target.shsFloat != this.shsFloat) {
				this.shsFloat = target.shsFloat;
				++count;
			}
			return count;
		}
	}
	
	@Override
	public String toString() {
		return CommonConstants.CSV_SURROUNDER_OF_FIELD + insiderOwnPerc + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ instOwnPerc + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ shsOutstand + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ shsFloat + CommonConstants.CSV_SURROUNDER_OF_FIELD;
	}
	

    private Long id;

    private Long companyId;

    private Double insiderOwnPerc;

    private Double instOwnPerc;

    private Integer shsOutstand;

    private Integer shsFloat;

    private Date createDt;

    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.id
     *
     * @return the value of company_statistics.id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.id
     *
     * @param id the value for company_statistics.id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.company_id
     *
     * @return the value of company_statistics.company_id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.company_id
     *
     * @param companyId the value for company_statistics.company_id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.insider_own_perc
     *
     * @return the value of company_statistics.insider_own_perc
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getInsiderOwnPerc() {
        return insiderOwnPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.insider_own_perc
     *
     * @param insiderOwnPerc the value for company_statistics.insider_own_perc
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setInsiderOwnPerc(Double insiderOwnPerc) {
        this.insiderOwnPerc = insiderOwnPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.inst_own_perc
     *
     * @return the value of company_statistics.inst_own_perc
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getInstOwnPerc() {
        return instOwnPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.inst_own_perc
     *
     * @param instOwnPerc the value for company_statistics.inst_own_perc
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setInstOwnPerc(Double instOwnPerc) {
        this.instOwnPerc = instOwnPerc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.shs_outstand
     *
     * @return the value of company_statistics.shs_outstand
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Integer getShsOutstand() {
        return shsOutstand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.shs_outstand
     *
     * @param shsOutstand the value for company_statistics.shs_outstand
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setShsOutstand(Integer shsOutstand) {
        this.shsOutstand = shsOutstand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.shs_float
     *
     * @return the value of company_statistics.shs_float
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Integer getShsFloat() {
        return shsFloat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.shs_float
     *
     * @param shsFloat the value for company_statistics.shs_float
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setShsFloat(Integer shsFloat) {
        this.shsFloat = shsFloat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.create_dt
     *
     * @return the value of company_statistics.create_dt
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.create_dt
     *
     * @param createDt the value for company_statistics.create_dt
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_statistics.last_update_dt
     *
     * @return the value of company_statistics.last_update_dt
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_statistics.last_update_dt
     *
     * @param lastUpdateDt the value for company_statistics.last_update_dt
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}