package org.maple.profitsystem.models;

import org.maple.profitsystem.constants.CommonConstants;
import org.maple.profitsystem.utils.TradingDateUtil;

public class StockQuoteModel implements Comparable<StockQuoteModel>{
	
	/**
	 * Sort by date ascending order
	 */
	@Override
	public int compareTo(StockQuoteModel o) {
		return -TradingDateUtil.betweenTradingDays(TradingDateUtil.convertNumDate2Date(this.getQuoteDate()), 
				TradingDateUtil.convertNumDate2Date(o.getQuoteDate()));
	}
	
	
	@Override
	public String toString() {
		return CommonConstants.CSV_SURROUNDER_OF_FIELD + this.quoteDate + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ this.open + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ this.close + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ this.high + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD  
				+ this.low + CommonConstants.CSV_SEPRATOR_BETWEEN_FIELD
				+ this.volume + CommonConstants.CSV_SURROUNDER_OF_FIELD;
	}
    private Long id;

    private Long companyId;

    private Integer quoteDate;

    private Double open;

    private Double close;

    private Double high;

    private Double low;

    private Integer volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.id
     *
     * @return the value of stock_quote.id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.id
     *
     * @param id the value for stock_quote.id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.company_id
     *
     * @return the value of stock_quote.company_id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.company_id
     *
     * @param companyId the value for stock_quote.company_id
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.quote_date
     *
     * @return the value of stock_quote.quote_date
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Integer getQuoteDate() {
        return quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.quote_date
     *
     * @param quoteDate the value for stock_quote.quote_date
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setQuoteDate(Integer quoteDate) {
        this.quoteDate = quoteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.open
     *
     * @return the value of stock_quote.open
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.open
     *
     * @param open the value for stock_quote.open
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.close
     *
     * @return the value of stock_quote.close
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.close
     *
     * @param close the value for stock_quote.close
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.high
     *
     * @return the value of stock_quote.high
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.high
     *
     * @param high the value for stock_quote.high
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.low
     *
     * @return the value of stock_quote.low
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.low
     *
     * @param low the value for stock_quote.low
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_quote.volume
     *
     * @return the value of stock_quote.volume
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_quote.volume
     *
     * @param volume the value for stock_quote.volume
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
}