package org.maple.profitsystem.mappers;

import java.util.List;

import org.maple.profitsystem.models.CompanyModel;

public interface CompanyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int insert(CompanyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int insertSelective(CompanyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    CompanyModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int updateByPrimaryKey(CompanyModel record);
    
    /**
     * Select all company model with base info
     * @return
     */
    List<CompanyModel> selectAll();
    
    List<CompanyModel> selectAllWithStatistics();
    
    List<CompanyModel> selectAllFull();
    
    int insertList(List<CompanyModel> records);
}