package org.maple.profitsystem.mappers;

import java.util.List;

import org.maple.profitsystem.models.StockQuoteModel;

public interface StockQuoteModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quote
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int insert(StockQuoteModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_quote
     *
     * @mbg.generated Fri Sep 15 15:30:45 CST 2017
     */
    int insertSelective(StockQuoteModel record);
    
    List<StockQuoteModel> selectListByCompanyId(long companyId);
    
    int insertList(List<StockQuoteModel> records);
}